export const customThemeJsonViewe = {
    '--w-rjv-color': '#EA4A6E',
    '--w-rjv-key-number': '#E95C73',
    '--w-rjv-key-string': '#BC5074',
    '--w-rjv-background-color': '#fafafa',
    '--w-rjv-line-color': '#6F6F6F',
    '--w-rjv-arrow-color': '#EA4A6E',
    '--w-rjv-edit-color': '#EA4A6E',
    '--w-rjv-info-color': '#6F6F6F',
    '--w-rjv-update-color': '#EA4A6E',
    '--w-rjv-copied-color': '#EA4A6E',
    '--w-rjv-copied-success-color': '#28a745',

    '--w-rjv-curlybraces-color': '#6F6F6F',
    '--w-rjv-colon-color': '#6F6F6F',
    '--w-rjv-brackets-color': '#6F6F6F',
    '--w-rjv-ellipsis-color': '#cb4b16',
    '--w-rjv-quotes-color': '#EA4A6E',
    '--w-rjv-quotes-string-color': '#ce9178',

    '--w-rjv-type-string-color': '#ce9178',
    '--w-rjv-type-int-color': '#6F6F6F',
    '--w-rjv-type-float-color': '#6F6F6F',
    '--w-rjv-type-bigint-color': '#6F6F6F',
    '--w-rjv-type-boolean-color': '#BC5074',
    '--w-rjv-type-date-color': '#6F6F6F',
    '--w-rjv-type-url-color': '#bf1200ff',
    '--w-rjv-type-null-color': '#BC5074',
    '--w-rjv-type-nan-color': '#859900',
    '--w-rjv-type-undefined-color': '#BC5074',
};
